<?php

namespace IMS\CoreBundle\Document\Follow;

use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;

/**
 * @MongoDB\Document(
 *      repositoryClass="IMS\CoreBundle\DocumentRepository\Follow\Follow",
 *      collection="follows"
 * )
 * @MongoDB\HasLifecycleCallbacks
 */
class Follow
{

    const
            TYPE_USER = 1,
            TYPE_SERVICE = 2,
            TYPE_TOOL = 3

    ;

    /**
     * Native autogenerated MongoId
     * @MongoDB\Id
     * 
     * @var $id
     */
    protected $id;

    /**
     * Account id, that followed the item 
     * @MongoDB\Int
     * @MongoDB\Indexes({
     *      @MongoDB\Index(name="follow_follower_asc", order="asc"),
     *      @MongoDB\Index(name="follow_follower_desc", order="desc")
     * })
     * @var integer $follower
     */
    protected $followerId;

    /**
     * Followed item id
     * @MongoDB\Int
     * @MongoDB\Indexes({
     *      @MongoDB\Index(name="follow_item_asc", order="asc"),
     *      @MongoDB\Index(name="follow_item_desc", order="desc")
     * })
     * 
     * @var integer $itemId
     */
    protected $itemId;

    /**
     * @MongoDB\Int
     * @MongoDB\Indexes({
     *      @MongoDB\Index(name="follow_type_asc", order="asc"),
     *      @MongoDB\Index(name="follow_type_desc", order="desc")
     * })
     * 
     * @var integer $type Followed item type. @see self::TYPE_%
     */
    protected $type;

    /**
     * Created at datetime
     * @MongoDB\Date
     * @MongoDB\Indexes({
     *      @MongoDB\Index(name="follow_createdat_asc", order="asc"),
     *      @MongoDB\Index(name="follow_createdat_desc", order="desc")
     * })
     * 
     * @var DateTime $createdAt
     */
    protected $createdAt;

    /**
     * @return string(MongoDB id)
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param integer $id 
     * @return self
     */
    public function setFollowerId($id)
    {
        $this->followerId = $id;
        return $this;
    }

    /**
     * @return integer
     */
    public function getFollowerId()
    {
        return $this->followerId;
    }

    /**
     * @param integer $id
     * @return self
     */
    public function setItemId($id)
    {
        $this->itemId = $id;
        return $this;
    }

    /**
     * @return integer
     */
    public function getItemId()
    {
        return $this->itemId;
    }

    /**
     * @param integer $type
     * @return self
     */
    public function setType($type)
    {
        $this->type = $type;
        return $this;
    }

    /**
     * @return integer
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param \DateTime $createdAt
     * @return self
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
        return $this;
    }

    /**
     * @param string $format DateTime presentation format. Defaults to [d-m-Y H:i:s]
     * @return string
     */
    public function getCreatedAt($format = 'd-m-Y H:i:s')
    {
        return $this->createdAt instanceof \DateTime ? $this->createdAt->format($format) : $this->createdAt;
    }

    /**
     * Set created at
     * @MongoDB\PrePersist
     */
    public function prePersist()
    {
        $this->setCreatedAt(new \DateTime());
    }

}
